INSERT INTO TB_UF (NOME, SIGLA, STATUS) VALUES ('SÃO PAULO', 'SP', 1);
INSERT INTO TB_UF (NOME, SIGLA, STATUS) VALUES ('RIO DE JANEIRO', 'RJ', 1);
INSERT INTO TB_UF (NOME, SIGLA, STATUS) VALUES ('Rondônia', 'RO', 1);
INSERT INTO TB_UF (NOME, SIGLA, STATUS) VALUES ('Acre', 'AC', 1);
INSERT INTO TB_UF (NOME, SIGLA, STATUS) VALUES ('Amazonas', 'AM', 1);
INSERT INTO TB_UF (NOME, SIGLA, STATUS) VALUES ('Roraima', 'RR', 1);
INSERT INTO TB_UF (NOME, SIGLA, STATUS) VALUES ('Pará', 'PA', 1);
INSERT INTO TB_UF (NOME, SIGLA, STATUS) VALUES ('Amapá', 'AP', 1);
INSERT INTO TB_UF (NOME, SIGLA, STATUS) VALUES ('Tocantins', 'TO', 1);